### ISSUE TITLE
安装依赖requirements.txt报错ModuleNotFoundError: No module named 'Cython'

### ISSUE THREAD

**Issue by HelloLittleJoey** [THUDM/GLM-4-Voice#101]
Collecting pynini==2.1.5 (from WeTextProcessing==1.0.3->-r .\requirements.txt (line 34))
  Using cached https://mirrors.aliyun.com/pypi/packages/86/63/6a720dbdf4e7358baa2ab206a51693f9c6e83d174179a95539f501bd4a34/pynini-2.1.5.tar.gz (627 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "e:\AI\github\GLM-4-Voice\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "e:\AI\github\GLM-4-Voice\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "e:\AI\github\GLM-4-Voice\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rzhxwl_6\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rzhxwl_6\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rzhxwl_6\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rzhxwl_6\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 22, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

**Comment by GZY219** [comment]
https://github.com/2noise/ChatTTS/issues/164#issue-2328974756

**Comment by Yuxy518** [comment]
执行命令：`conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing==1.0.2` 之后
重新安装依赖 requirements.txt 就好了
