### ISSUE TITLE
glm-4-voice-decoder does not appear to have a file named config.json

### ISSUE THREAD

**Issue by zkbaba** [THUDM/GLM-4-Voice#15]
(glm4-voice) PS E:\project\LLM\GLM-4-Voice-main> python web_demo.py --tokenizer-path ./weight/glm-4-voice-tokenizer --model-path ./weight/glm-4-voice-decoder
Traceback (most recent call last):
  File "E:\project\LLM\GLM-4-Voice-main\web_demo.py", line 252, in <module>
    initialize_fn()
  File "E:\project\LLM\GLM-4-Voice-main\web_demo.py", line 51, in initialize_fn
    glm_tokenizer = AutoTokenizer.from_pretrained(args.model_path, trust_remote_code=True)
  File "D:\Anaconda3\envs\glm4-voice\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 854, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "D:\Anaconda3\envs\glm4-voice\lib\site-packages\transformers\models\auto\configuration_auto.py", line 976, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\Anaconda3\envs\glm4-voice\lib\site-packages\transformers\configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\Anaconda3\envs\glm4-voice\lib\site-packages\transformers\configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "D:\Anaconda3\envs\glm4-voice\lib\site-packages\transformers\utils\hub.py", line 373, in cached_file
    raise EnvironmentError(
OSError: ./weight/glm-4-voice-decoder does not appear to have a file named config.json. Checkout 'https://huggingface.co/./weight/glm-4-voice-decoder/tree/None' for available files.
报错：是需要将configuration.json重命名为config.json嘛？？

**Comment by zkbaba** [comment]
我路径搞错了
