### ISSUE TITLE
text模式下报错：AssertionError: Expected a list of lists or list of tuples.

### ISSUE THREAD

**Issue by shirubei** [THUDM/GLM-4-Voice#24]
Text模式下测试了一句，可以听到回复的声音，但是后台Log提示如下错误：

Traceback (most recent call last):
  File "D:\anaconda3\envs\glm4voice\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\anaconda3\envs\glm4voice\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\anaconda3\envs\glm4voice\lib\site-packages\gradio\blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\anaconda3\envs\glm4voice\lib\site-packages\gradio\blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\anaconda3\envs\glm4voice\lib\site-packages\gradio\components\chatbot.py", line 259, in postprocess
    assert isinstance(
AssertionError: Expected a list of lists or list of tuples. Received: {'role': 'user', 'content': '听说华为的Mate 70 pro也出来了。'}

**Comment by Beam-wi** [comment]
gradio 版本太低，

可以把所有history.append()中添加内容改成list如：
web_demo.py 94 行 history.append({"role": "user", "content": input_text}) 改成：
history.append(["user", input_text])

**Comment by trackcan** [comment]
> gradio 版本太低，
> 
> 可以把所有history.append()中添加内容改成list如： web_demo.py 94 行 history.append({"role": "user", "content": input_text}) 改成： history.append(["user", input_text])

这种修改不行，报的是response的 AssertionError: Expected a list of lists or list of tuples.
