### ISSUE TITLE
大佬们！你们开发时，能不能用Python 新库，按照你的github上的配置，表示报错阿。

### ISSUE THREAD

**Issue by xiaoxiaoshutong** [THUDM/GLM-4-Voice#41]
<img width="590" alt="image" src="https://github.com/user-attachments/assets/d938de9f-02aa-40f1-b2ea-26d39c944b6b">
一堆依赖库，还拉不起来。用最新库吧。
还有能不能，减少一下这个源码大小。这个源码35G阿，不跑的情况下35。9B应该就是9G，不能再逆天了。
小弟比较菜，一直喜欢追随智源。所以，每个出来的产品，我都用了智源的API。
随便解决一下依赖库的问题吧。
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 186, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 232, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
    super().__init__(
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 314, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 706, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/Users/hucheng/Projects/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/private/var/folders/3b/7m2pl47d4qj8ykw542rzrk0c0000gn/T/pip-build-env-uxtds0k7/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'

**Comment by Djooxx** [comment]
一样的问题
![image](https://github.com/user-attachments/assets/d2d93999-dd4e-4d43-9bf7-26fc069525f4)

**Comment by dahu1** [comment]
用了python3.10 可以装好

**Comment by zRzRzRzRzRzRzR** [comment]
试一下这套配置
```
torch==2.5.0
torchaudio==2.5.0
diffusers==0.31.0
accelerate==1.0.1
transformers<4.46.0
peft==0.13.2
bitsandbytes==0.44.1
deepspeed==0.15.3
gradio==5.4.0
fastapi==0.115.4
inflect==7.4.0
librosa==0.10.2.post1
lightning==2.4.0
matplotlib==3.9.2
modelscope==1.19.2
omegaconf==2.3.0
onnxruntime-gpu==1.19.2
openai-whisper==20240930
protobuf==5.28.3
tensorboard==2.18.0
hyperpyyaml==1.2.2
hydra-core==1.3.2
gdown==5.2.0
wget==3.2
conformer==0.3.2
```
Python 3.12.7

**Comment by Djooxx** [comment]
> 试一下这套配置,其他配置都移除掉，能否运行
> 
> ```
> torch==2.5.0
> torchaudio==2.5.0
> diffusers==0.31.0
> accelerate==1.0.1
> transformers<4.46.0
> peft==0.13.2
> bitsandbytes==0.44.1
> deepspeed==0.15.3
> gradio==5.4.0
> fastapi==0.115.4
> inflect==7.4.0
> librosa==0.10.2.post1
> lightning==2.4.0
> matplotlib==3.9.2
> modelscope==1.19.2
> omegaconf==2.3.0
> onnxruntime-gpu==1.19.2
> openai-whisper==20240930
> protobuf==5.28.3
> tensorboard==2.18.0
> hyperpyyaml==1.2.2
> hydra-core==1.3.2
> gdown==5.2.0
> wget==3.2
> conformer==0.3.2
> ```
> 
> Python 3.12.7

不行报错
![image](https://github.com/user-attachments/assets/465277a9-a38f-4883-8cf6-e2ac79e9e48a)
有docker计划吗？

**Comment by xiaoxiaoshutong** [comment]
我又来了，可能还真不是库的问题
<img width="1371" alt="image" src="https://github.com/user-attachments/assets/c8740b0f-3f69-47d4-afd4-228587730f93">
我用https://colab.research.google.com/drive/1edmXLa3UE-iKUHr_Hi4EMbUbXwtZc071#scrollTo=iouEIc8k1RRL
也是报错，明明就有model_server.py就是报错。
<img width="1104" alt="image" src="https://github.com/user-attachments/assets/7c9b1122-ad9d-4de5-a846-19002159a94a">
嗯，浪费心情了。

**Comment by xiaoxiaoshutong** [comment]
Loading checkpoint shards:  75% 3/4 [01:07<00:22, 22.60s/it]
Traceback (most recent call last):
  File "/content/GLM-4-Voice/model_server.py", line 143, in <module>
    worker = ModelWorker(args.model_path, args.dtype, args.device)
  File "/content/GLM-4-Voice/model_server.py", line 74, in __init__
    self.glm_model = AutoModel.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 559, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3960, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 4434, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 961, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/modeling.py", line 416, in set_module_tensor_to_device
    new_value = value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU

**Comment by xiaoxiaoshutong** [comment]
尽力了

**Comment by zRzRzRzRzRzRzR** [comment]
GPU需要24G左右的显存，通常文本一长还会超过这个显存
