### ISSUE TITLE
strange flash attention error

### ISSUE THREAD

**Issue by silvacarl2** [THUDM/GLM-4-Voice#63]
python web_demo.py --tokenizer-path  THUDM/glm-4-voice-tokenizer --model-path THUDM/glm-4-voice-9b --flow-path ./glm-4-voice-decoder
Traceback (most recent call last):
  File "/mnt/d/Dropbox/Developer-Tools/whisper/GLM-4-Voice/web_demo.py", line 10, in <module>
    import torchaudio
  File "/home/silvacarl/.local/lib/python3.10/site-packages/torchaudio/__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
  File "/home/silvacarl/.local/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "/home/silvacarl/.local/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "/home/silvacarl/.local/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/silvacarl/.local/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN3c1010Dispatcher17runRecordFunctionERN2at14RecordFunctionESt17reference_wrapperIKNS_14FunctionSchemaEENS_11DispatchKeyE

have not figured out how to resolve it.

**Comment by zRzRzRzRzRzRzR** [comment]
This is likely because your CUDA and Torch are not correctly bound
